import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import Header from '@/components/Header/Header';
import { Montserrat } from 'next/font/google';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

const montserrat = Montserrat({
  subsets: ['latin'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.className} antialiased grid grid-cols-4 sm:grid-cols-8 md:grid-cols-12 gap-2 sm:gap-5 min-h-screen `}>
        <div className="px-4 md:px-0 col-start-1 md:col-start-2 col-span-4 sm:col-span-8 md:col-span-10">
          <Header />
          {children}
        </div>
      </body>
    </html>
  );
}
